import { Fragment, useState, useEffect } from 'react'
import Head from 'next/head'
import TopPage from '../../../components/TopPage'
import placeholderImg from '../../../public/logo.jpg'
import Link from 'next/link'
import Image from 'next/image'


export async function getStaticPaths() {
    const res_departments = await fetch('http://localhost:3000/api/departments')
    const res_services = await fetch('http://localhost:3000/api/services')
    const departments = await res_departments.json()
    const services = await res_services.json()

    const paths = services.reduce((acc, service) => {
        departments.forEach((department) => {
            acc.push({
                params: { service: service.slug.toString(), department: department.slug.toString() },
            })
        })
        return acc
    }, [])

    return { paths, fallback: false }
}

export async function getStaticProps(context) {

    const { service, department } = context.params;
    const res_department = await fetch(`http://localhost:3000/api/${department}`)
    const res_service = await fetch(`http://localhost:3000/api/services/${service}`)
    const departments = await res_department.json()
    const services = await res_service.json()

    return {
        props: { department: departments, service: services },
    }
}

const Department = ({ service, department }) => {

    const [search, setSearch] = useState('');
    const [cities, setCities] = useState([]);

    const onSearch = (e) => {
        setSearch(e.currentTarget.value);
    };

    useEffect(() => {
        const results = department.cities.filter(city =>
            city.name.toLowerCase().includes(search.toLowerCase()) ||
            city.slug.toLowerCase().includes(search.toLowerCase())
        );
        setCities(results);
    }, [search]);

    return (
        <Fragment>


            <Head>
                <title>Create Next App</title>
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content="Generated by create next app" />
            </Head>

            <TopPage image={placeholderImg} title={`Nos services de ${service.name} - ${department.name} (${department.code})`} />
            <div className="flex min-h-[50vh] flex-col items-center pb-2 ">
                <main className="container z-30 text-center pt-16 px-10">
                    <h1 className='text-5xl z-40 mb-16 text-start'>
                        <div className="absolute inset-x-0 h-[300px] skew-y-[0.75deg] bg-green-700 drop-shadow-[0_2px_10px_rgba(0,0,0,0.1)]">
                            <div className="absolute inset-x-0 top-10 h-[200px] -skew-y-[1.4deg] bg-green-600 drop-shadow-[0_2px_10px_rgba(0,0,0,0.1)]">
                            </div>
                        </div>
                        <div className='skew-y-0 font-bold text-white pt-24'>
                            Nous allons jusqu'à chez vous !
                        </div>
                    </h1>
                    <input type="text" className="skew-y-0 w-full font-semibold h-20 drop-shadow-[0_2px_10px_rgba(0,0,0,0.05)] focus:drop-shadow-[0_8px_30px_rgba(0,0,0,0.15)] px-6 mb-2 text-2xl placeholder:text-white focus:placeholder:text-gray-600 text-white focus:text-gray-600 bg-white/40 focus:bg-white/80 backdrop-blur-2xl rounded-lg outline-none duration-200 transition-all" placeholder="Rechercher une ville" onChange={onSearch} />
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-5 py-12">
                        {cities.length ? cities.map((city) => {
                            return (

                                <Link href={`/${service.slug}/${department.slug}/${city.slug}`} key={city.id}>
                                    <div className="card group flex h-52 drop-shadow-[0_2px_10px_rgba(0,0,0,0.05)] hover:drop-shadow-[0_10px_30px_rgba(0,0,0,0.05)] shadow-color-gray-900 rounded-xl ring-1 ring-slate-100 duration-100 overflow-hidden">
                                        <Image
                                            id='image'
                                            src={`/images/${department.slug}_${city.slug}.png`}
                                            alt='Image'
                                            style={{ objectFit: "cover" }}
                                            fill={true}
                                        />
                                        <div className="absolute bottom-0 px-6 py-4 group-hover:bottom-2 duration-200">
                                            <h3 className="text-2xl font-bold text-start pb-2 mb-2 border-b-4 border-b-green-500">{city.name}</h3>
                                        </div>
                                    </div>
                                </Link>
                            )
                        }) : ""
                        }
                    </div>
                    {cities.length ? "" : <div className="text-2xl font-semibold text-gray-500">Oh ! Il semblerait que la ville "{search}" n'existe pas</div>}
                </main>
            </div >
        </Fragment >
    )
}

export default Department
